CREATE TABLE usuari.user(
    id SERIAL, 
    user_name VARCHAR(100) NOT NULL UNIQUE,
    password_user VARCHAR(255) NOT NULL,
	CONSTRAINT pk_user PRIMARY KEY (id)
);
CREATE INDEX idx_user_id ON usuari.user(id);  
INSERT INTO usuari.user (user_name, password_user) VALUES
('johndoe', 'password123'),
('janedoe', 'securepass'),
('mike89', 'mikepass'),
('sarah_s', 'sarah123'),
('admin1', 'adminpass'),
('lucas_m', 'lucas789'),
('paul_a', 'paulpass'),
('nina_k', 'nina456'),
('sam_r', 'sam123'),
('lisa_w', 'lisa_pass'),
('roberto_g', 'robert321'),
('maria_p', 'maria987'),
('carlos_a', 'admin321'),
('andrea_q', 'andrea654'),
('manuel_x', 'manuel852'),
('sofia_m', 'sofia741'),
('pablo_d', 'pablo963'),
('diego_t', 'diego159'),
('fernando_v', 'fer456'),
('valeria_z', 'vale789'),
('jose_r', 'admin789'),
('karla_s', 'karla321'),
('diana_f', 'diana852'),
('raul_c', 'raul753'),
('elena_g', 'elena369'),
('alberto_b', 'alberto258'),
('ricardo_n', 'ricardo159'),
('antonio_k', 'antonio357'),
('victoria_w', 'victoria753'),
('sebastian_h', 'sebas951'),
('angela_y', 'angela741'),
('marco_l', 'marco147'),
('gabriel_o', 'gabriel369'),
('eduardo_t', 'eduardo852'),
('camila_v', 'camila123'),
('isabel_u', 'isabel456'),
('javier_p', 'javier963'),
('beatriz_n', 'beatriz789'),
('francisco_q', 'francisco654'),
('hugo_x', 'hugo321'),
('margarita_d', 'margarita987'),
('nicolas_r', 'admin456'),
('patricia_g', 'patricia741'),
('ramiro_z', 'ramiro258'),
('oscar_m', 'oscar357'),
('felipe_v', 'felipe159'),
('clara_c', 'clara159'),
('esteban_f', 'esteban951'),
('alejandro_k', 'alejandro753'),
('monica_t', 'monica963'),
('daniel_y', 'daniel369'),
('santiago_w', 'santiago852'),
('lorena_h', 'lorena456'),
('ignacio_l', 'ignacio741'),
('xavier_o', 'xavier321'),
('adriana_j', 'adriana123'),
('gerardo_k', 'gerardo456'),
('veronica_m', 'veronica789'),
('octavio_p', 'octavio123'),
('rene_q', 'rene456'),
('silvia_r', 'silvia789');